name: "Cachix"
on:
  pull_request:
  push:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: aira
        attributes: ros_comm
        nixBuildArgs: '--option sandbox false'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
